import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from  '/public/dev-ed-wave.png';
import design from '/public/design.png';
import code from '/public/code.png';
import consulting from '/public/consulting.png';
import web1 from '/public/web1.png';
import web2 from '/public/web2.png';
import web3 from '/public/web3.png';
import web4 from '/public/web4.png';
import web5 from '/public/web5.png';
import web6 from '/public/web6.png';


export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Dimitri Marco Portfolio</title>
        <meta nam="description" content="Generated By Cre"></meta>
        <link rel="icon" href='/favicon.ico'></link>
      </Head> 
    <main className="bg-white px-10 md:px-20 lg:px-40">

      <section className=" min-h-screen">

        <nav className="py-10 mb-12 flex justify-between"> 
          <h2 className="text-2xl font-burtons">Timi Bolaji</h2>
          <ul className='flex items-center'>
            <li className="cursor-pointer text-2xl">
              <BsFillMoonStarsFill />
            </li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8" href="#">Resume</a></li>
          </ul>
        </nav>

        <div className="text-center p-10">
          <h2 className="text-5xl text-teal-600 py-2 font-medium md:text-6xl">Timi Bolaji Idowu</h2>
          <h3 className="text-2xl py-2">Software Engineer</h3>
          <p className='leading-8 py-5 text-md text-gray-800 md:text-xl max-w-lg mx-auto'>Freenclancer providing services for programming and needs. Join me and let's get started</p>
        </div>

        <div className="flex text-5xl justify-center gap-16 py-3 text-gray-600">
         <AiFillTwitterCircle />
         <AiFillLinkedin />
         <AiFillYoutube />
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
          <Image src={deved} layout='fill' objectFit='cover' />
          <h3>Beautiful Design</h3>
          <p></p>

        </div>

      </section>
      <section>
        <div>
          <h3 className='text-3xl py-1'>Services I Offer</h3>
          <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
           <span className='text-teal-500'>Quae laboriosam </span>labore laborum? Vero consequuntur maiores adipisci cupiditate numquam quam quisquam!</p>
           <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. At distinctio illo ea consequatur nostrum nulla asperiores unde quisquam, dolorum architecto.</p>
        </div>
        <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'> 
            <Image src={design} width={100} height={100} />
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>Creating elegant designs suited for your design theory</p>
            <h4 className='text-teal-600 py-4'>Design Tools I use</h4>
            <p className='text-gray-800 py-1'>Illustrator</p>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'> 
            <Image src={code} width={100} height={100} />
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>Creating elegant designs suited for your design theory</p>
            <h4 className='text-teal-600 py-4'>Design Tools I use</h4>
            <p className='text-gray-800 py-1'>Illustrator</p>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'> 
            <Image src={consulting} width={100} height={100} />
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>Creating elegant designs suited for your design theory</p>
            <h4 className='text-teal-600 py-4'>Design Tools I use</h4>
            <p className='text-gray-800 py-1'>Illustrator</p>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
          </div>
        </div>
      </section>
      <section>
      <div>
          <h3 className='text-3xl py-1'>Portfolio</h3>
          <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
           <span className='text-teal-500'>Quae laboriosam </span>labore laborum? Vero consequuntur maiores adipisci cupiditate numquam quam quisquam!</p>
           <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. At distinctio illo ea consequatur nostrum nulla asperiores unde quisquam, dolorum architecto.</p>
        </div>
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap '>
          <div className='basis-1/3 flex-1'><Image src={web1}  className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
          <div className='basis-1/3 flex-1'><Image src={web2}  className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
          <div className='basis-1/3 flex-1'><Image src={web3}  className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
          <div className='basis-1/3 flex-1'><Image src={web4}  className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
          <div className='basis-1/3 flex-1'><Image src={web5}  className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
          <div className='basis-1/3 flex-1'><Image src={web6}  className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>

        </div>
      </section>
    </main>
    </div> 
    
  );
}
